### ISSUE TITLE
doctrine/orm 2.6.1 bug

### ISSUE THREAD

**Issue by wendel841** [Monofony/SymfonyStarter#100]
**ApiCore version affected**: 1.x.y

**Description**  
Doctrine version 2.6.1 bugged? After cloning master branch and composer install i got:

```
In UnitOfWork.php line 2718:
                                                                                                    
  Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
                                                                                                    

In UnitOfWork.php line 2718:
                                                                                                    
  Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
```

**Steps to reproduce**  
Clone master branch
composer install
php bin/console

**Possible Solution**  
I updated doctrine/orm with composer and problem is gone.

composer update doctrine/orm

**Comment by loic425** [comment]
Thanks a lot # @wendel841 
I dit not reproduce it but I upgraded doctrine/orm component.
