### ISSUE TITLE
Does anyone configured Rbac plugin of sylius ?

### ISSUE THREAD

**Issue by harikt** [Monofony/SymfonyStarter#185]
I was trying out https://packagist.org/packages/sylius/rbac-plugin .

Came across some issues, fixed some of them, but not sure how the customers are configured to get the right permission etc.

It seems good to have by default.

**Comment by loic425** [comment]
@harikt Sylius plugin requires sylius/sylius package (like other Sylius plugins).
So this is not a good idea. Moreover, you can build a lot of projects without a dynamic RBAC system.
Symfony security configuration are often enough.

If you need it on a project, you can easily integrate your own system based on Sylius Rbac plugin. I did that last year.

**Comment by harikt** [comment]
ok, thanks. I don't want to integrate currently for any project. Just playing around.

But the form has certain fields like `administrationRole` which was causing issue. I want to look more how to add that field in the `AdminUserType` .

The backend url `/admin/administration-roles/new` etc was not having enough permission. The fixtures were not loading. Things were blocking. So thought it may be good to have.
