### ISSUE TITLE
Admin user is now disabled

### ISSUE THREAD

**Issue by Loocos** [Monofony/SymfonyStarter#265]
**ApiCore version affected**: Demo version

**Description**  
I just wanna take a look to this app. I tried to log me in the admin panel but it said than the account is disabled.

**Steps to reproduce**  
Try to connect to admin panel on the demo app in the README.MD

**Possible Solution**  
Enable the admin user

Thank you!

**Comment by loic425** [comment]
Hello,
I reloaded the data fixtures. You can now connect to the admin panel.
I also added a cron task to reload database every hour.

**Comment by loic425** [comment]
Thank you @Lowcost-dev !
